spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        druid:
            first:  #数据源1
                url: jdbc:mysql://192.168.0.173:3306/pamperpet?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=true
                username: dev
                password: 123123
            second:  #数据源2
                url: jdbc:mysql://192.168.0.173:3306/pamperpet?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=true
                username: dev
                password: 123123
          
server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    port: 8090
    connection-timeout: 5000
    context-path: /
                
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.demo.entity.*.entity
                